version: 2
jobs:
  build:
    docker:
      - image: samimideksa/allinone:latest
    steps:
      - checkout
      - run:
          name: Install Requests
          command: python3.6 -m pip install requests
      - run:
          name: Get Models
          command: cd allinonemodels && wget http://144.76.153.5/aio_model/freeze2.h5
      - run:
          name: install GRPC
          command: python3.6 -m pip install grpcio grpcio-tools
      - run:
          name: Generate GRPC files
          command:  cd grpc && python3.6 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. grpc/all_in_one.proto
      - run:
          name: Run Tests
          command: python3.6 -m unittest test_rpc_call.TestSuiteGrpc

          

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
