# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detect_image.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detect_image.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x64\x65tect_image.proto\"\x1b\n\nInputImage\x12\r\n\x05Image\x18\x01 \x01(\x0c\"\x1c\n\x0bOutputImage\x12\r\n\x05Image\x18\x01 \x01(\x0c\x32\x37\n\tImageDemo\x12*\n\x0b\x44\x65tectImage\x12\x0b.InputImage\x1a\x0c.OutputImage\"\x00\x62\x06proto3')
)




_INPUTIMAGE = _descriptor.Descriptor(
  name='InputImage',
  full_name='InputImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Image', full_name='InputImage.Image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=49,
)


_OUTPUTIMAGE = _descriptor.Descriptor(
  name='OutputImage',
  full_name='OutputImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Image', full_name='OutputImage.Image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['InputImage'] = _INPUTIMAGE
DESCRIPTOR.message_types_by_name['OutputImage'] = _OUTPUTIMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputImage = _reflection.GeneratedProtocolMessageType('InputImage', (_message.Message,), dict(
  DESCRIPTOR = _INPUTIMAGE,
  __module__ = 'detect_image_pb2'
  # @@protoc_insertion_point(class_scope:InputImage)
  ))
_sym_db.RegisterMessage(InputImage)

OutputImage = _reflection.GeneratedProtocolMessageType('OutputImage', (_message.Message,), dict(
  DESCRIPTOR = _OUTPUTIMAGE,
  __module__ = 'detect_image_pb2'
  # @@protoc_insertion_point(class_scope:OutputImage)
  ))
_sym_db.RegisterMessage(OutputImage)



_IMAGEDEMO = _descriptor.ServiceDescriptor(
  name='ImageDemo',
  full_name='ImageDemo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=81,
  serialized_end=136,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectImage',
    full_name='ImageDemo.DetectImage',
    index=0,
    containing_service=None,
    input_type=_INPUTIMAGE,
    output_type=_OUTPUTIMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGEDEMO)

DESCRIPTOR.services_by_name['ImageDemo'] = _IMAGEDEMO

# @@protoc_insertion_point(module_scope)
