# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import detect_image_pb2 as detect__image__pb2


class ImageDemoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DetectImage = channel.unary_unary(
        '/ImageDemo/DetectImage',
        request_serializer=detect__image__pb2.InputImage.SerializeToString,
        response_deserializer=detect__image__pb2.OutputImage.FromString,
        )


class ImageDemoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DetectImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageDemoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DetectImage': grpc.unary_unary_rpc_method_handler(
          servicer.DetectImage,
          request_deserializer=detect__image__pb2.InputImage.FromString,
          response_serializer=detect__image__pb2.OutputImage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImageDemo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
