# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: all_in_one.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='all_in_one.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x61ll_in_one.proto\":\n\x13\x46\x61\x63\x65\x41lignmentHeader\x12#\n\rsource_bboxes\x18\x01 \x03(\x0b\x32\x0c.BoundingBox\"2\n\x0f\x41llInOneRequest\x12\r\n\x05image\x18\x01 \x01(\t\x12\x10\n\x08\x46ileType\x18\x02 \x01(\t\"[\n\x10\x41llInOneResponse\x12\x0e\n\x06gender\x18\x01 \x03(\t\x12\r\n\x05smile\x18\x02 \x03(\t\x12\x0b\n\x03\x41ge\x18\x03 \x03(\x05\x12\x1b\n\x05\x62_box\x18\x04 \x03(\x0b\x32\x0c.BoundingBox\"s\n\x14\x46\x61\x63\x65\x41lignmentRequest\x12&\n\x06header\x18\x01 \x01(\x0b\x32\x14.FaceAlignmentHeaderH\x00\x12 \n\x0bimage_chunk\x18\x02 \x01(\x0b\x32\t.ImageRGBH\x00\x42\x11\n\x0fheader_or_chunk\"\x1d\n\x1b\x46\x61\x63\x65\x41lignmentResponseHeader\"|\n\x15\x46\x61\x63\x65\x41lignmentResponse\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1c.FaceAlignmentResponseHeaderH\x00\x12 \n\x0bimage_chunk\x18\x02 \x01(\x0b\x32\t.ImageRGBH\x00\x42\x11\n\x0fheader_or_chunk\"\x1b\n\x08ImageRGB\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"9\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\"\x1f\n\x07Point2D\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"1\n\x0e\x46\x61\x63\x65\x44\x65tections\x12\x1f\n\tface_bbox\x18\x01 \x03(\x0b\x32\x0c.BoundingBox\"@\n\rFaceLandmarks\x12\x16\n\x0elandmark_model\x18\x01 \x01(\t\x12\x17\n\x05point\x18\x02 \x03(\x0b\x32\x08.Point2D\"p\n\x18\x46\x61\x63\x65LandmarkDescriptions\x12\x16\n\x0elandmark_model\x18\x01 \x01(\t\x12\x1c\n\x14landmark_description\x18\x02 \x03(\t\x12\x1e\n\x0clandmark_avg\x18\x03 \x03(\x0b\x32\x08.Point2D\">\n\x12\x46\x61\x63\x65LandmarkModels\x12(\n\x05model\x18\x01 \x03(\x0b\x32\x19.FaceLandmarkDescriptions2\x7f\n\x08\x41llInOne\x12\x31\n\x08\x41llInOne\x12\x10.AllInOneRequest\x1a\x11.AllInOneResponse\"\x00\x12@\n\tAlignFace\x12\x15.FaceAlignmentRequest\x1a\x16.FaceAlignmentResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)




_FACEALIGNMENTHEADER = _descriptor.Descriptor(
  name='FaceAlignmentHeader',
  full_name='FaceAlignmentHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_bboxes', full_name='FaceAlignmentHeader.source_bboxes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=78,
)


_ALLINONEREQUEST = _descriptor.Descriptor(
  name='AllInOneRequest',
  full_name='AllInOneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='AllInOneRequest.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FileType', full_name='AllInOneRequest.FileType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=130,
)


_ALLINONERESPONSE = _descriptor.Descriptor(
  name='AllInOneResponse',
  full_name='AllInOneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gender', full_name='AllInOneResponse.gender', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='smile', full_name='AllInOneResponse.smile', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Age', full_name='AllInOneResponse.Age', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b_box', full_name='AllInOneResponse.b_box', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=223,
)


_FACEALIGNMENTREQUEST = _descriptor.Descriptor(
  name='FaceAlignmentRequest',
  full_name='FaceAlignmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='FaceAlignmentRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_chunk', full_name='FaceAlignmentRequest.image_chunk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='header_or_chunk', full_name='FaceAlignmentRequest.header_or_chunk',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=225,
  serialized_end=340,
)


_FACEALIGNMENTRESPONSEHEADER = _descriptor.Descriptor(
  name='FaceAlignmentResponseHeader',
  full_name='FaceAlignmentResponseHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=371,
)


_FACEALIGNMENTRESPONSE = _descriptor.Descriptor(
  name='FaceAlignmentResponse',
  full_name='FaceAlignmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='FaceAlignmentResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_chunk', full_name='FaceAlignmentResponse.image_chunk', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='header_or_chunk', full_name='FaceAlignmentResponse.header_or_chunk',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=373,
  serialized_end=497,
)


_IMAGERGB = _descriptor.Descriptor(
  name='ImageRGB',
  full_name='ImageRGB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='ImageRGB.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=526,
)


_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='BoundingBox.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='BoundingBox.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='BoundingBox.w', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='BoundingBox.h', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=585,
)


_POINT2D = _descriptor.Descriptor(
  name='Point2D',
  full_name='Point2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point2D.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point2D.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=587,
  serialized_end=618,
)


_FACEDETECTIONS = _descriptor.Descriptor(
  name='FaceDetections',
  full_name='FaceDetections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_bbox', full_name='FaceDetections.face_bbox', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=669,
)


_FACELANDMARKS = _descriptor.Descriptor(
  name='FaceLandmarks',
  full_name='FaceLandmarks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='landmark_model', full_name='FaceLandmarks.landmark_model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point', full_name='FaceLandmarks.point', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=671,
  serialized_end=735,
)


_FACELANDMARKDESCRIPTIONS = _descriptor.Descriptor(
  name='FaceLandmarkDescriptions',
  full_name='FaceLandmarkDescriptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='landmark_model', full_name='FaceLandmarkDescriptions.landmark_model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landmark_description', full_name='FaceLandmarkDescriptions.landmark_description', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landmark_avg', full_name='FaceLandmarkDescriptions.landmark_avg', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=737,
  serialized_end=849,
)


_FACELANDMARKMODELS = _descriptor.Descriptor(
  name='FaceLandmarkModels',
  full_name='FaceLandmarkModels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='FaceLandmarkModels.model', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=851,
  serialized_end=913,
)

_FACEALIGNMENTHEADER.fields_by_name['source_bboxes'].message_type = _BOUNDINGBOX
_ALLINONERESPONSE.fields_by_name['b_box'].message_type = _BOUNDINGBOX
_FACEALIGNMENTREQUEST.fields_by_name['header'].message_type = _FACEALIGNMENTHEADER
_FACEALIGNMENTREQUEST.fields_by_name['image_chunk'].message_type = _IMAGERGB
_FACEALIGNMENTREQUEST.oneofs_by_name['header_or_chunk'].fields.append(
  _FACEALIGNMENTREQUEST.fields_by_name['header'])
_FACEALIGNMENTREQUEST.fields_by_name['header'].containing_oneof = _FACEALIGNMENTREQUEST.oneofs_by_name['header_or_chunk']
_FACEALIGNMENTREQUEST.oneofs_by_name['header_or_chunk'].fields.append(
  _FACEALIGNMENTREQUEST.fields_by_name['image_chunk'])
_FACEALIGNMENTREQUEST.fields_by_name['image_chunk'].containing_oneof = _FACEALIGNMENTREQUEST.oneofs_by_name['header_or_chunk']
_FACEALIGNMENTRESPONSE.fields_by_name['header'].message_type = _FACEALIGNMENTRESPONSEHEADER
_FACEALIGNMENTRESPONSE.fields_by_name['image_chunk'].message_type = _IMAGERGB
_FACEALIGNMENTRESPONSE.oneofs_by_name['header_or_chunk'].fields.append(
  _FACEALIGNMENTRESPONSE.fields_by_name['header'])
_FACEALIGNMENTRESPONSE.fields_by_name['header'].containing_oneof = _FACEALIGNMENTRESPONSE.oneofs_by_name['header_or_chunk']
_FACEALIGNMENTRESPONSE.oneofs_by_name['header_or_chunk'].fields.append(
  _FACEALIGNMENTRESPONSE.fields_by_name['image_chunk'])
_FACEALIGNMENTRESPONSE.fields_by_name['image_chunk'].containing_oneof = _FACEALIGNMENTRESPONSE.oneofs_by_name['header_or_chunk']
_FACEDETECTIONS.fields_by_name['face_bbox'].message_type = _BOUNDINGBOX
_FACELANDMARKS.fields_by_name['point'].message_type = _POINT2D
_FACELANDMARKDESCRIPTIONS.fields_by_name['landmark_avg'].message_type = _POINT2D
_FACELANDMARKMODELS.fields_by_name['model'].message_type = _FACELANDMARKDESCRIPTIONS
DESCRIPTOR.message_types_by_name['FaceAlignmentHeader'] = _FACEALIGNMENTHEADER
DESCRIPTOR.message_types_by_name['AllInOneRequest'] = _ALLINONEREQUEST
DESCRIPTOR.message_types_by_name['AllInOneResponse'] = _ALLINONERESPONSE
DESCRIPTOR.message_types_by_name['FaceAlignmentRequest'] = _FACEALIGNMENTREQUEST
DESCRIPTOR.message_types_by_name['FaceAlignmentResponseHeader'] = _FACEALIGNMENTRESPONSEHEADER
DESCRIPTOR.message_types_by_name['FaceAlignmentResponse'] = _FACEALIGNMENTRESPONSE
DESCRIPTOR.message_types_by_name['ImageRGB'] = _IMAGERGB
DESCRIPTOR.message_types_by_name['BoundingBox'] = _BOUNDINGBOX
DESCRIPTOR.message_types_by_name['Point2D'] = _POINT2D
DESCRIPTOR.message_types_by_name['FaceDetections'] = _FACEDETECTIONS
DESCRIPTOR.message_types_by_name['FaceLandmarks'] = _FACELANDMARKS
DESCRIPTOR.message_types_by_name['FaceLandmarkDescriptions'] = _FACELANDMARKDESCRIPTIONS
DESCRIPTOR.message_types_by_name['FaceLandmarkModels'] = _FACELANDMARKMODELS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FaceAlignmentHeader = _reflection.GeneratedProtocolMessageType('FaceAlignmentHeader', (_message.Message,), dict(
  DESCRIPTOR = _FACEALIGNMENTHEADER,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:FaceAlignmentHeader)
  ))
_sym_db.RegisterMessage(FaceAlignmentHeader)

AllInOneRequest = _reflection.GeneratedProtocolMessageType('AllInOneRequest', (_message.Message,), dict(
  DESCRIPTOR = _ALLINONEREQUEST,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:AllInOneRequest)
  ))
_sym_db.RegisterMessage(AllInOneRequest)

AllInOneResponse = _reflection.GeneratedProtocolMessageType('AllInOneResponse', (_message.Message,), dict(
  DESCRIPTOR = _ALLINONERESPONSE,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:AllInOneResponse)
  ))
_sym_db.RegisterMessage(AllInOneResponse)

FaceAlignmentRequest = _reflection.GeneratedProtocolMessageType('FaceAlignmentRequest', (_message.Message,), dict(
  DESCRIPTOR = _FACEALIGNMENTREQUEST,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:FaceAlignmentRequest)
  ))
_sym_db.RegisterMessage(FaceAlignmentRequest)

FaceAlignmentResponseHeader = _reflection.GeneratedProtocolMessageType('FaceAlignmentResponseHeader', (_message.Message,), dict(
  DESCRIPTOR = _FACEALIGNMENTRESPONSEHEADER,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:FaceAlignmentResponseHeader)
  ))
_sym_db.RegisterMessage(FaceAlignmentResponseHeader)

FaceAlignmentResponse = _reflection.GeneratedProtocolMessageType('FaceAlignmentResponse', (_message.Message,), dict(
  DESCRIPTOR = _FACEALIGNMENTRESPONSE,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:FaceAlignmentResponse)
  ))
_sym_db.RegisterMessage(FaceAlignmentResponse)

ImageRGB = _reflection.GeneratedProtocolMessageType('ImageRGB', (_message.Message,), dict(
  DESCRIPTOR = _IMAGERGB,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:ImageRGB)
  ))
_sym_db.RegisterMessage(ImageRGB)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDINGBOX,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:BoundingBox)
  ))
_sym_db.RegisterMessage(BoundingBox)

Point2D = _reflection.GeneratedProtocolMessageType('Point2D', (_message.Message,), dict(
  DESCRIPTOR = _POINT2D,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:Point2D)
  ))
_sym_db.RegisterMessage(Point2D)

FaceDetections = _reflection.GeneratedProtocolMessageType('FaceDetections', (_message.Message,), dict(
  DESCRIPTOR = _FACEDETECTIONS,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:FaceDetections)
  ))
_sym_db.RegisterMessage(FaceDetections)

FaceLandmarks = _reflection.GeneratedProtocolMessageType('FaceLandmarks', (_message.Message,), dict(
  DESCRIPTOR = _FACELANDMARKS,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:FaceLandmarks)
  ))
_sym_db.RegisterMessage(FaceLandmarks)

FaceLandmarkDescriptions = _reflection.GeneratedProtocolMessageType('FaceLandmarkDescriptions', (_message.Message,), dict(
  DESCRIPTOR = _FACELANDMARKDESCRIPTIONS,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:FaceLandmarkDescriptions)
  ))
_sym_db.RegisterMessage(FaceLandmarkDescriptions)

FaceLandmarkModels = _reflection.GeneratedProtocolMessageType('FaceLandmarkModels', (_message.Message,), dict(
  DESCRIPTOR = _FACELANDMARKMODELS,
  __module__ = 'all_in_one_pb2'
  # @@protoc_insertion_point(class_scope:FaceLandmarkModels)
  ))
_sym_db.RegisterMessage(FaceLandmarkModels)



_ALLINONE = _descriptor.ServiceDescriptor(
  name='AllInOne',
  full_name='AllInOne',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=915,
  serialized_end=1042,
  methods=[
  _descriptor.MethodDescriptor(
    name='AllInOne',
    full_name='AllInOne.AllInOne',
    index=0,
    containing_service=None,
    input_type=_ALLINONEREQUEST,
    output_type=_ALLINONERESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AlignFace',
    full_name='AllInOne.AlignFace',
    index=1,
    containing_service=None,
    input_type=_FACEALIGNMENTREQUEST,
    output_type=_FACEALIGNMENTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALLINONE)

DESCRIPTOR.services_by_name['AllInOne'] = _ALLINONE

# @@protoc_insertion_point(module_scope)
