# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import all_in_one_pb2 as all__in__one__pb2


class AllInOneStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AllInOne = channel.unary_unary(
        '/AllInOne/AllInOne',
        request_serializer=all__in__one__pb2.AllInOneRequest.SerializeToString,
        response_deserializer=all__in__one__pb2.AllInOneResponse.FromString,
        )


class AllInOneServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AllInOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AllInOneServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AllInOne': grpc.unary_unary_rpc_method_handler(
          servicer.AllInOne,
          request_deserializer=all__in__one__pb2.AllInOneRequest.FromString,
          response_serializer=all__in__one__pb2.AllInOneResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AllInOne', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
